name: Deploy Laravel App to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Laravel App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1" # Adjust PHP version as per your application
          extensions: mbstring, intl, bcmath, openssl, pdo, tokenizer
          coverage: none

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Adjust Node.js version as per your application

      - name: Install Node.js Dependencies
        run: npm install

      - name: Build Assets
        run: npm run build

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      # - name: Run Tests
      #   run: php artisan test

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Sync Files to VPS
        env:
          SSH_PASS: ${{ secrets.SSH_PASS }}
        run: |
          sshpass -p "$SSH_PASS" rsync -avz --exclude="storage/" --exclude=".env" --exclude=".git/" -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_DIR }}

      - name: Install Dependencies on VPS
        env:
          SSH_PASS: ${{ secrets.SSH_PASS }}
        run: |
          sshpass -p "$SSH_PASS" ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          cd ${{ secrets.DEPLOY_DIR }} &&
          composer install --no-dev --optimize-autoloader &&
          php artisan migrate --force &&
          php artisan optimize
          "
