name: Deploy Laravel App to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Laravel App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Sync Files to VPS
        run: |
          rsync -avz --exclude="storage/" --exclude=".env" --exclude=".git/" ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_DIR }}

      - name: Install Dependencies
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          cd ${{ secrets.DEPLOY_DIR }} &&
          composer install --no-dev --optimize-autoloader &&
          php artisan migrate --force &&
          php artisan config:cache &&
          php artisan route:cache &&
          php artisan view:cache
          "

      - name: Restart PHP and Web Server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          sudo systemctl restart php8.1-fpm &&
          sudo systemctl restart nginx
          "
